spring:

  application:
    name:post-it-app

  datasource:
    url:  jdbc:postgresql://db:5432/notes
    username: admin
    password: pass

  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8081

